// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLhDe68n6HtnvaXiS_EibC727L_r5w6kM',
    appId: '1:883490309996:web:4d976639eb881962725549',
    messagingSenderId: '883490309996',
    projectId: 'orchidcareapp',
    authDomain: 'orchidcareapp.firebaseapp.com',
    storageBucket: 'orchidcareapp.firebasestorage.app',
    measurementId: 'G-E2XFYQ4X80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk-J0zpiDeS0rwOFKewbK6ZZLIRJ-3HZA',
    appId: '1:883490309996:android:28f1949c6232a314725549',
    messagingSenderId: '883490309996',
    projectId: 'orchidcareapp',
    storageBucket: 'orchidcareapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvwCypb8oAO8NICNAuJrous0Tfhv7g5yY',
    appId: '1:883490309996:ios:312c489d2cbd1ee5725549',
    messagingSenderId: '883490309996',
    projectId: 'orchidcareapp',
    storageBucket: 'orchidcareapp.firebasestorage.app',
    iosBundleId: 'com.example.orchidCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvwCypb8oAO8NICNAuJrous0Tfhv7g5yY',
    appId: '1:883490309996:ios:312c489d2cbd1ee5725549',
    messagingSenderId: '883490309996',
    projectId: 'orchidcareapp',
    storageBucket: 'orchidcareapp.firebasestorage.app',
    iosBundleId: 'com.example.orchidCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLhDe68n6HtnvaXiS_EibC727L_r5w6kM',
    appId: '1:883490309996:web:43953847cdc88029725549',
    messagingSenderId: '883490309996',
    projectId: 'orchidcareapp',
    authDomain: 'orchidcareapp.firebaseapp.com',
    storageBucket: 'orchidcareapp.firebasestorage.app',
    measurementId: 'G-1295JNFX71',
  );
}
